version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg-database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: go-api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: bookstore
      DB_PORT: 5432
    ports:
      - "8080:8080"

volumes:
  pg_data:
